name: test

on:
  - pull_request
  - push

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    container:
      image: osrf/ros:humble-desktop
    strategy:
      matrix:
        os: [ubuntu-22.04]
        ros_distro: [humble]
      fail-fast: false
    steps:
      - name: Install deps
        run:
          sudo apt-get update
          sudo apt-get install -y wget python3-vcstool python3-colcon-coveragepy-result
          sudo apt-get install -y ros-${{ matrix.ros_distro }}-ament-lint-auto ros-${{ matrix.ros_distro }}-ament-lint-common
      - name: Install ament_lint
        run: sudo apt-get install -y python3-ament-lint-auto python3-ament-lint-common
      - name: build and test
        uses: ros-tooling/action-ros-ci@0.2.6
        with:
          package-name: plansys2_gpsr
          target-ros2-distro: humble
          import-token: ${{ secrets.WORKFLOW_TEST }}
          colcon-defaults: |
            {
              "test": {
                "parallel-workers" : 1
              }
            }
