name: test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    container:
      image: osrf/ros:humble-desktop
    strategy:
      matrix:
        os: [ubuntu-22.04]
      fail-fast: false
    steps:
      - name: Install deps
        run: sudo apt-get update && sudo apt-get install -y wget python3-colcon-coveragepy-result

      
      - name: Run tests
        run: |
          . /opt/ros/humble/setup.sh
          colcon test --event-handlers console_direct+ --packages-select plansys2_gpsr
